### ISSUE TITLE
[Model Request] mightbe/Better-PairRM

### ISSUE THREAD

**Issue by StableFluffy** [allenai/reward-bench#102]
https://huggingface.co/mightbe/Better-PairRM

I made few fixes on PairRM's dataset filter process and truncate etc..

As a result I got at least 15% performance.

Code and prompt template on huggingface repo.

Thank you.

**Comment by natolambert** [comment]
@StableFluffy really cool. Do you have time to open a PR that extends the existing code in `models/pairrm.py` or make sure inference works? Looks like it shouldn't be too bad.

**Comment by natolambert** [comment]
Closed with #104
