### ISSUE TITLE
Is eval set on huggingface the eval set or train set?

### ISSUE THREAD

**Issue by andrewsiah** [allenai/reward-bench#106]
Hi @natolambert et al,

We are reading the paper and the 2.98K filtered dataset at huggingface.

![Screenshot 2024-04-13 at 9 45 51 PM](https://github.com/allenai/reward-bench/assets/31041391/0d7165af-fc1b-4edc-9753-efbb3b92d759)

https://huggingface.co/datasets/allenai/reward-bench

I am curious if the huggingface 2.98K filtered data is the actual evaluation data used to evaluate on the leaderboard? 

Cause I looked into the code and saw this line in `utils.py`.

```
CORE_EVAL_SET = "ai2-adapt-dev/rm-benchmark-dev"
EXTRA_PREF_SETS = "allenai/pref-test-sets"
```

When I went to ai2-adapt-dev, I saw that it is a private dataset.

Asking cause we're hoping to know if we can/should train on the huggingface dataset for our reward model to fairly compare on the leaderboard.

Thanks!

**Comment by natolambert** [comment]
Ah, @andrewsiah it's all one evaluation set (no training split). Yeah, missed this line, the final dataset is here. https://huggingface.co/datasets/allenai/reward-bench
That link was just a temporary home. Will update it now.
