### ISSUE TITLE
Do we need to add system prompt when training/evaluating RM?

### ISSUE THREAD

**Issue by hank0316** [allenai/reward-bench#134]
Hi,

I want to know if we should add a system prompt when training and evaluating our reward models. For instance, I have supervised fine-tuned LLaMA2-7B on the Alpaca SFT 10k subset, and I use the same chat template for the tokenizer as the one in [LLaMA2-7B-Chat](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf/blob/f5db02db724555f92da89c216ac04704f23d4590/tokenizer_config.json#L12). The system prompt used in Meta's paper is shown in the screenshot below, which is included manually during my SFT procedure.

My understanding is that since we add a system prompt when collecting responses from LLaMA2 during RLHF, the system prompt becomes part of the overall prompt seen by LLaMA2. Therefore, it seems logical to include the system prompt in the query sent to the reward model to better assess the quality of the generated responses. However, if we apply the tokenizer's chat template, as is the default behavior in Reward-Bench, the system prompt might not be included.

Could you please clarify if the system prompt should be added during the training and evaluation of reward models?

![image](https://github.com/allenai/reward-bench/assets/55573473/2410c989-2606-4566-bcc0-8f49182bd8f2)

Thank you!

**Comment by natolambert** [comment]
Hey @hank0316 to the best of my knowledge, no, but you can likely do it.
Reward models normally use the same chat template from IFT which allows it, but it's not well studied.
