### ISSUE TITLE
Model Test Application

### ISSUE THREAD

**Issue by wjxxyz** [allenai/reward-bench#149]
Hello, my lab has recently fine-tuned a new model and I'd like to contribute my model to your leaderboard, please refer to https://huggingface.co/CIR-AMS/BTRM_Qwen2_7b_0613 for details

**Comment by natolambert** [comment]
@wjxxyz can you modify the checkpoint so it can be loaded from HuggingFace without special code? Right now the file is nested in folders so it requires code modification / special handling.

**Comment by wjxxyz** [comment]
> @wjxxyz can you modify the checkpoint so it can be loaded from HuggingFace without special code? Right now the file is nested in folders so it requires code modification / special handling.您可以修改检查点，以便无需特殊代码即可从 HuggingFace 加载它吗？现在，该文件嵌套在文件夹中，因此需要代码修改/特殊处理。

I've changed the checkpoints and the web link is https://huggingface.co/CIR-AMS/BTRM_Qwen2_7b_0613/tree/main, thank you

**Comment by natolambert** [comment]
Thanks! @wjxxyz I also opened #155 to make bfloat16 work correctly.
