### ISSUE TITLE
Add New reward models 

### ISSUE THREAD

**Issue by YangRui2015** [allenai/reward-bench#150]
Two new reward models are available: Ray2333/GRM-llama3-8B-distill (https://huggingface.co/Ray2333/GRM-llama3-8B-distill), Ray2333/Gemma-2B-rewardmodel-baseline (https://huggingface.co/Ray2333/Gemma-2B-rewardmodel-baseline). They are both finetuned on opensource datasets, achieving average scores of 86.1 and 73.7 locally. 

Details are on the huggingface pages.

**Comment by natolambert** [comment]
Nice, will add these shortly with `Ray2333/GRM-Gemma-2B-sftreg` and `Ray2333/GRM-llama3-8B-sftreg`. Cool paper!

**Comment by YangRui2015** [comment]
Thank you!
