### ISSUE TITLE
The metrics of gemma-2-27b-it is not matched with the metrics on leaderboard

### ISSUE THREAD

**Issue by ToSev7en** [allenai/reward-bench#163]
I evaluated gemma-2-27b-it 
{'Chat': 0.8938547486033519, 'Chat Hard': 0.6085526315789473, 'Safety': 0.8867946647946647, 'Reasoning': 0.7705588066786708} 

while

![image](https://github.com/user-attachments/assets/2c6fb743-5e59-4865-9e36-bd330dc4a591)

**Comment by chrisliu298** [comment]
When you run the script, did you set `"attn_implementation": "flash_attention_2"`? I noticed a performance degradation when flash attention is not used for `gemma-2-27b-it`. However, this is not the case for other models I've tried.

**Comment by natolambert** [comment]
Also @ToSev7en, can you share how you ran it? I ran it with TotherAI API because VLLM was broken when I implemented it. 
We could figure out how to store the scores for both, if you work out the details Chris mentioned.

**Comment by ToSev7en** [comment]
> When you run the script, did you set `"attn_implementation": "flash_attention_2"`? I noticed a performance degradation when flash attention is not used for `gemma-2-27b-it`. However, this is not the case for other models I've tried.

I downloaded `gemma-2-27b-it`  from hugginface hub，and  here comes the `config.json` :

```json
{
  "architectures": [
    "Gemma2ForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "attn_logit_softcapping": 50.0,
  "bos_token_id": 2,
  "cache_implementation": "hybrid",
  "eos_token_id": 1,
  "final_logit_softcapping": 30.0,
  "head_dim": 128,
  "hidden_act": "gelu_pytorch_tanh",
  "hidden_activation": "gelu_pytorch_tanh",
  "hidden_size": 4608,
  "initializer_range": 0.02,
  "intermediate_size": 36864,
  "max_position_embeddings": 8192,
  "model_type": "gemma2",
  "num_attention_heads": 32,
  "num_hidden_layers": 46,
  "num_key_value_heads": 16,
  "pad_token_id": 0,
  "query_pre_attn_scalar": 144,
  "rms_norm_eps": 1e-06,
  "rope_theta": 10000.0,
  "sliding_window": 4096,
  "sliding_window_size": 4096,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.42.0.dev0",
  "use_cache": true,
  "vocab_size": 256000
}
```

Thers is no `"attn_implementation": "flash_attention_2"` indeed, so should I add it into the `config.json` ?

**Comment by ToSev7en** [comment]
> Also @ToSev7en, can you share how you ran it? I ran it with TotherAI API because VLLM was broken when I implemented it. We could figure out how to store the scores for both, if you work out the details Chris mentioned.

@natolambert I ran it with `run_generative.py` base on the latest version of `vllm`, and it works but not up to the performance on leaderboard. I will try the details Chris mentioned, thx.

**Comment by chrisliu298** [comment]
@ToSev7en, the issue occurred when I used a gemma-2-27b-it trained as a sequence classifier. However, I'm not sure if the same problem would happen with a generative model. I'll try it when I have the time.

**Comment by natolambert** [comment]
Interesting @ToSev7en that the API was better... this is normal evaluation rabbit holes :)
