### ISSUE TITLE
Add a new generative model

### ISSUE THREAD

**Issue by YeZiyi1998** [allenai/reward-bench#189]
We would like to add Con-J-Qwen2-7B by
```
python scripts/run_generative.py --model="ZiyiYe/Con-J-Qwen2-7B"
```
This is our local test results:
{'Chat': 0.9189944134078212, 'Chat Hard': 0.7982456140350878, 'Safety': 0.8797297297297297, 'Reasoning': 0.881871692039068}
Thanks for your help in advance.

**Comment by natolambert** [comment]
Done! Thanks for committing your code directly to the library.
