### ISSUE TITLE
Add A Series of New Generative Models

### ISSUE THREAD

**Issue by bittersweet1999** [allenai/reward-bench#204]
Hi RewardBench Team 👋,

We have updated a series of generative models:
[opencompass/CompassJudger-1-32B-Instruct](https://huggingface.co/opencompass/CompassJudger-1-32B-Instruct)
[opencompass/CompassJudger-1-14B-Instruct](https://huggingface.co/opencompass/CompassJudger-1-14B-Instruct)
[opencompass/CompassJudger-1-7B-Instruct](https://huggingface.co/opencompass/CompassJudger-1-7B-Instruct)
[opencompass/CompassJudger-1-1.5B-Instruct](https://huggingface.co/opencompass/CompassJudger-1-1.5B-Instruct)

Our local evaluation metrics for the model is listed as bellow:
For **CompassJudger-1-32B-Instruct**:
{'Chat': 0.9776536312849162, 'Chat Hard': 0.6557017543859649, 'Safety': 0.8613455949455949, 'Reasoning': 0.9221162765318929}
For **CompassJudger-1-14B-Instruct**:
{'Chat': 0.9748603351955307, 'Chat Hard': 0.6228070175438597, 'Safety': 0.8453248157248157, 'Reasoning': 0.9247200169149343}
For **CompassJudger-1-7B-Instruct**:
{'Chat': 0.9776536312849162, 'Chat Hard': 0.6052631578947368, 'Safety': 0.8470778518778519, 'Reasoning': 0.8951922027609537}
For **CompassJudger-1-1.5B-Instruct**:
{'Chat': 0.9636871508379888, 'Chat Hard': 0.49451754385964913, 'Safety': 0.7813390663390664, 'Reasoning': 0.6959131336279806}

To Run Evaluation Script
For these generative models, it's okay to evaluate them with the default scripts/run_generative.py script. Just as below code:
```
export VLLM_WORKER_MULTIPROC_METHOD=spawn
cd reward-bench
python scripts/run_generative.py --model=opencompass/CompassJudger-1-32B-Instruct --num_gpus 4
```
We would like to add these series of new generative models to the RewardBench LeaderBoard.

Thank you!

**Comment by natolambert** [comment]
Running now. Will be visible upon next restart.
