### ISSUE TITLE
Add Nvidia RMs (and Nemo compatibility)

### ISSUE THREAD

**Issue by natolambert** [allenai/reward-bench#76]
See below!
https://huggingface.co/models?library=nemo&search=RM

This involves converting to HF format or adding nemo compatibility, if anyone has time!

**Comment by natolambert** [comment]
Closing because stale.

**Comment by Riashat** [comment]
Hello @natolambert 

Is there any update on this? Or do you know if anyone has used Nvidia nemo RMs in Reward-Bench or M-Reward-Bench for compatibility?

**Comment by natolambert** [comment]
@Riashat no update. Thankfully Nvidia has been releasing more -hf checkpoints, so less of an issue now.
